---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: helloworld
  namespace: default
spec:
  parentRefs:
    - namespace: envoy-gateway
      name: public
      sectionName: mtls-helloworld
  hostnames:
    - "helloworld.example.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: helloworld
          port: 80