---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 1h
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: envoy-repo
        namespace: default
      chart: gateway-helm
      version: 1.6.1

  # https://github.com/envoyproxy/gateway/tree/main/charts/gateway-helm
  values: {}