---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-mtls
  namespace: envoy-gateway
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: public
    sectionName: mtls-helloworld
  tls:
    clientValidation:
      caCertificateRefs:
      - kind: "Secret"
        name: "ca-certs"
        namespace: envoy-gateway