---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nginx
  namespace: develop
spec:
  image: nginx
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nginx
  namespace: develop
spec:
  imageRepositoryRef:
    name: nginx
  policy:
    semver:
      range: 1.20.1
