---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  selector:
    app: helloworld
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: dockercloud/hello-world:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 50Mi
              cpu: 10m
            requests:
              memory: 50Mi
              cpu: 10m
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 80
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 80
