---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: vero-charts-git
        namespace: flux-system
      chart: ./metrics-server
  values: {}
