---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1h
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: hashicorp-repo
        namespace: default
      chart: vault
      version: 0.31.0
  # https://github.com/hashicorp/vault-helm/blob/main/values.yaml
  values:
    injector:
      enabled: false

    server:
      enabled: true
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 256Mi
      service:
        type: NodePort

      updateStrategyType: RollingUpdate

      ingress:
        enabled: false

      dataStorage:
        enabled: false

      auditStorage:
        enabled: true
        size: 10Gi
        mountPath: "/vault/audit"

      standalone:
        enabled: true
        config: |
          ui = true

          storage "dynamodb" {
            ha_enabled = "true"
            table = "vault-data"
          }

          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = 1

            telemetry {
              unauthenticated_metrics_access = "true"
            }
          }

          telemetry {
            disable_hostname = true
          }

          seal "awskms" {
            region     = "us-east-2"
            kms_key_id = "alias/vault-sealing-key"
          }

      serviceAccount:
        create: true
        name: "vault"

      extraEnvironmentVars:
        AWS_DEFAULT_REGION: us-east-2
        AWS_KMS_ENDPOINT: http://localstack.localstack.svc:4566
        AWS_DYNAMODB_ENDPOINT: http://localstack.localstack.svc:4566
        AWS_ACCESS_KEY_ID: fake
        AWS_SECRET_ACCESS_KEY: fake

    # Vault UI
    ui:
      enabled: true
      serviceType: NodePort

    # secrets-store-csi-driver-provider-vault
    csi:
      enabled: false
